language: node_js
node_js:
 - "10"
 - "9"
services: mongodb
script: 
 - "npm test"
cache:
  directories:
    - "node_modules"
      
env:
  - PORT=4000
  - MONGOURL=mongodb://localhost:27017/marketing-website
  - DOMAIN=localhost
